### ISSUE TITLE
Add source jars to maven build

### ISSUE THREAD

**Issue by andhen** [subclipse/svnclientadapter#32]
For users developing against svnclientadapter it would be helpful if source jars were published in the maven repo.

I had reasonable success with the standard plugin setup:
```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-source-plugin</artifactId>
  <executions>
    <execution>
      <id>attach-sources</id>
      <goals>
        <goal>jar</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```
It should pick up the correct pom from ${project.build.outputDirectory}/META-INF/MANIFEST.MF by default.

(Applying this to the underlying JavaHL module would be nice, too. I didn't create a separate issue for that project.)

**Comment by markphip** [comment]
I made this change and published a 1.9.7 release to Maven if you want to verify.

Sorry this took so long, I had turned off my Github notifications by mistake.
