### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by marinoszago** [subclipse/svnclientadapter#36]
Hi all, 

I would like to use svn client adapter with svn kit. However svn kit requires to have source code open which is something I cannot do. If I use svn client adapter am I covered from that aspect and use it without open sourcing the code? 

Thank you

**Comment by markphip** [comment]
Licensing issues are for you to figure out. Generally if you are distributing SvnKit then you have to comply with its license. So if you are looking to get around its license the place to start is to not distribute it with your app.

**Comment by marinoszago** [comment]
Thank you
