### ISSUE TITLE
Javahl client adapter is not available

### ISSUE THREAD

**Issue by marinoszago** [subclipse/svnclientadapter#37]
Excuse me, 
what do I need to make it work with Javahl?

Thank you

**Comment by markphip** [comment]
JavaHL is a native C library provided with SVN itself. So you typically need to have the SVN command line client installed AND the JavaHL library. How you get that varies by OS and packaging system.  There is some information here: https://github.com/subclipse/subclipse/wiki

On the svnClientAdapter side you then need the JavaHL adapter AND the JavaHL JAR that matches the native library. Meaning the JAR and native libraries need to be from the same version of SVN.  The JavaHL JAR contains the JNI methods to load and call the native library method.

**Comment by marinoszago** [comment]
Thank you very much
