### ISSUE TITLE
command line client status parser fail on summary line

### ISSUE THREAD

**Issue by mariohofmann** [subclipse/svnclientadapter#38]
The command line status parser fails on summary line reported by svn.

Status lines reported by svn command line client:
![grafik](https://user-images.githubusercontent.com/26171236/66140635-bd31ee80-e602-11e9-859f-24344635b88c.png)

Error caused while parsing command line:
![grafik](https://user-images.githubusercontent.com/26171236/66140700-db97ea00-e602-11e9-8960-c651e91b62e3.png)

**Comment by markphip** [comment]
The command line adapter has not been maintained since probably SVN 1.4 if not earlier

**Comment by markphip** [comment]
Presumably fixed by PR #39
