### ISSUE TITLE
"Command line client adapter is not available" error even when svn client is installed in the environment

### ISSUE THREAD

**Issue by shahrukhali4** [subclipse/svnclientadapter#45]
Trying to do svn operations from my java application using svnclientadapter commandline adapter 1.11.0 but getting below error:
org.tigris.subversion.svnclientadapter.SVNClientException: Command line client adapter is not available
	at org.tigris.subversion.svnclientadapter.commandline.CmdLineClientAdapterFactory.setup(CmdLineClientAdapterFactory.java:69)

Application is running on Tomcat Server in a CentOS environment which have svn 1.11.0 client installed, "svn --version" gives correct result.

**Comment by markphip** [comment]
I doubt the command line client adapter works. It has not been maintained in over 10 years and never supported the full set of methods. It works by parsing the command line output. I would guess that the svn --version output has changed in a way that it does not know how to pass.

You should use the JavaHL or SVNKit adapter. Those are the only ones supported. Or just drive the command line client directly if you just need to execute some SVN commands.

**Comment by shahrukhali4** [comment]
Moving from command line client adapter at this point will be difficult for me as i have already written a lot of implementation on top of that i can consider moving from it in future as it kind of works for me in most environments the above mentioned issue occurs only in some specific environments .   
On further analysis, it appears that the command line adapter works for an environment in which "svn --version" gives following output:
$ svn --version
svn, version 1.11.0 (r1845130)
compiled Nov  1 2018, 12:32:40 on x86_64-redhat-linux-gnu
Copyright (C) 2018 The Apache Software Foundation.
This software consists of contributions made by many people;
see the NOTICE file for more information.
Subversion is open source software, see http://subversion.apache.org/

The environment in which it is not working and giving "Command line client adapter is not available" error gives the output of "svn --version" with some LC warnings which seems to be causing problem, below is  the output with warning:
$ svn --version
svn: warning: cannot set LC_CTYPE locale
svn: warning: environment variable LC_CTYPE is UTF-8
svn: warning: please check that your locale name is correct
svn, version 1.11.0 (r1845130)
   compiled Nov  1 2018, 12:32:40 on x86_64-redhat-linux-gnu

Copyright (C) 2018 The Apache Software Foundation.

This could be causing the issue, but on checking the code of CommandLine.java in command line adapter source code i can see some logic handling LC_TYPES errors not sure if its working correctly or not.

**Comment by shahrukhali4** [comment]
Got the issue finally!!
The above analysis turns out to be correct the error was occuring due to the warnings that were appearing in svn --version output, that i mentioned in previous comment.
The warnings that were appearing while doing "svn --version" (i.e.svn: warning: cannot set LC_CTYPE locale ) were happening due to an issue with ssh client of MacOS mentioned in the this link http://thegreyblog.blogspot.com/2012/02/fixing-mac-os-x-lions-ssh-utf-8-issues.html , doing the steps mentioned in the link resolved the warnings and resolved the error, it works like a charm now.
