### ISSUE TITLE
Getting -1 as revision after commit. couldn't able to identify RCA.

### ISSUE THREAD

**Issue by cholank** [subclipse/svnclientadapter#93]
### Discussed in https://github.com/subclipse/svnclientadapter/discussions/92

<div type='discussions-op-text'>

<sup>Originally posted by **cholank** July 17, 2023</sup>
Hello Team, Greetings ..!

Please let me know on what scenarios we get (-1) invalid Revision number after commit. This behavior is occurring very rare , we couldn't able to identify the root cause as the Exception is being suppressed in the **CmdLineClientAdapter.java** Line# 562 [URL](https://github.com/subclipse/svnclientadapter/blob/ff9446b7edeeeb2298c7e82d6144feea8b4c26e7/cmdline/src/main/java/org/tigris/subversion/svnclientadapter/commandline/CmdLineClientAdapter.java#L71)

we would like to know the root cause when the revision is returned as (-1)

Thanks in Advance ..!</div>

**Comment by cholank** [comment]
Hi Team, is there any update on the issue ?

**Comment by markphip** [comment]
None of this is really being actively maintained. In the case of the CmdLine Adapter in particular, that stopped being maintained in the SVN 1.4 days (> 15 years ago now).

svnClientAdapter mainly served Subclipse and that only used the JavaHL and SVNKit adapters. The CmdLine adapter just bootstrapped the project in the beginning.

To be clear though, none of them are being actively maintained any longer though. JavaHL has been fairly stable though so still works up through the 1.14 releases for what is exposed in the adapter.

**Comment by cholank** [comment]
Thanks for the update Mark..!
